Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -9,7 +9,10 @@ jobs:
   data-transfer-and-clean:
     runs-on: ubuntu-latest
     steps:
-
+      - name: Checkout repo
+        uses: actions/checkout@v4
+        with:
+          token: ${{ secrets.ACTIONS_TOKEN }}  # Use your personal access token
       - name: Install jq
         run: sudo apt-get update && sudo apt-get install jq
 
@@ -18,6 +21,14 @@ jobs:
         run: |
           curl "http://zimbor.go.ro/solr/jobs/select?q=*:*&fl=job_title,job_link,company,hiringOrganization.name,country,remote,jobLocationType,validThrough,city,sursa,id,county&rows=1000000&wt=json&indent=true" -o backup.json
           jq '.response.docs' backup.json > cleaned_backup.json
+          
+      - name: Commit and Push cleaned_backup.json
+        run: |
+          git config --local user.email "action@github.com"
+          git config --local user.name "GitHub Action"
+          git add cleaned_backup.json
+          git commit -m "Update cleaned_backup.json" || exit 0  # Do not fail the action if no changes
+          git push          
 
       - name: Define Backup Servers
         run: echo "BACKUP_SERVERS=http://peviitor.go.ro:80,http://zimbor.go.ro:8985,http://srvalx.duckdns.org:8983" >> $GITHUB_ENV
